
import type { Hostel } from './types';

export const allHostels: Hostel[] = [
  {
    id: 1,
    name: 'Chandra Boys Hostel',
    location: 'Hyderabad',
    fullAddress: 'Near ABC College, XYZ Road, Hyderabad',
    description: `A modern, secure, and fully furnished hostel offering comfortable living with high-speed Wi-Fi, daily meals, and 24/7 security. Ideal for students and professionals, located close to schools, colleges, and transport hubs. This hostel has 6 floors with 10 rooms on each. It includes 2 rooms with 2-sharing, 3 rooms with 4-sharing, and 5 rooms with 5-sharing, with both AC and non-AC options available.`,
    price: 6500, // Monthly starting price
    rating: 4.8,
    reviews: 1250,
    images: [
      'https://img.freepik.com/premium-photo/png-architecture-building-city-neighbourhood-isolated-white-background-text-area_660230-15676.jpg',
      'https://img.freepik.com/premium-photo/png-architecture-building-city-neighbourhood-isolated-white-background-text-area_660230-15676.jpg',
      'https://img.freepik.com/premium-photo/png-architecture-building-city-neighbourhood-isolated-white-background-text-area_660230-15676.jpg',
    ],
    facilities: [
      'wifi',
      'water',
      'power',
      'cctv',
      'cleaning',
      'laundry',
      'fridge',
      'study',
      'purifier',
      'lift',
      'parking',
      'visitors',
      'ac',
      'food',
    ],
    roomOptions: [
      { type: 'AC', sharing: 2, price: 8000 },
      { type: 'AC', sharing: 3, price: 7500 },
      { type: 'Non-AC', sharing: 2, price: 7000 },
      { type: 'Non-AC', sharing: 3, price: 6500 },
    ],
    rateCard: {
      ac: { day: 400, twoDays: 750, weekly: 2500, monthly: 8000, yearly: 85000 },
      nonAc: { day: 300, twoDays: 600, weekly: 2000, monthly: 6500, yearly: 70000 },
    },
    inclusions: [
      '3-Time Meals (as per menu)',
      'Room Access with Bed and Fan',
      'Wi-Fi + Power Backup',
      'Access to Washing Machine',
      'Daily Cleaning',
      '24/7 Security',
    ],
    paymentOptions: ['UPI / Net Banking', 'Cash at Hostel Office', 'Monthly EMI Available for Yearly Plan'],
    foodMenu: [
      {
        day: 'Monday',
        breakfast: 'Idli & Sambar',
        lunch: 'Rice, Dal, Mixed Veg Curry',
        dinner: 'Chapati, Paneer Butter Masala',
      },
      {
        day: 'Tuesday',
        breakfast: 'Dosa & Chutney',
        lunch: 'Lemon Rice, Aloo Fry',
        dinner: 'Rice, Sambar, Egg Curry',
      },
      {
        day: 'Wednesday',
        breakfast: 'Upma',
        lunch: 'Rice, Rajma, Bhindi Fry',
        dinner: 'Chapati, Chicken Curry',
      },
      {
        day: 'Thursday',
        breakfast: 'Poori & Kurma',
        lunch: 'Vegetable Biryani, Raita',
        dinner: 'Rice, Tomato Dal, Aloo Fry',
      },
      {
        day: 'Friday',
        breakfast: 'Pongal',
        lunch: 'Rice, Chole, Cabbage Fry',
        dinner: 'Chapati, Egg Curry',
      },
      {
        day: 'Saturday',
        breakfast: 'Paratha',
        lunch: 'Rice, Dal, Gobi Manchurian',
        dinner: 'Rice, Dal, Mixed Veg',
      },
      {
        day: 'Sunday',
        breakfast: 'Masala Dosa',
        lunch: 'Chicken Biryani, Raita',
        dinner: 'Chapati, Paneer Curry',
      },
    ],
    securityDeposit: 2000,
    securityInfo: [
      'Biometric Access Control',
      'Fire Safety Equipment',
      'Wardens on Duty',
      'Night Curfew Policy: 10:00 PM',
    ],
  },
  {
    id: 2,
    name: 'Ruchi Sree Hostel',
    location: 'Vijayawada',
    fullAddress: 'Vaddeswaram, Vijayawada, Andhra Pradesh',
    description: 'A top-rated premium hostel known for its quality food, clean rooms, and excellent amenities. Perfect for students of nearby universities.',
    price: 7000,
    rating: 4.9,
    reviews: 890,
    images: [
      'https://img.squareyards.com/secondaryPortal/IN_638837942694078415-2505250624292429.png',
      'https://img.squareyards.com/secondaryPortal/IN_638837942694078415-2505250624292429.png',
      'https://img.squareyards.com/secondaryPortal/IN_638837942694078415-2505250624292429.png',
    ],
    facilities: ['wifi', 'ac', 'food', 'laundry', 'cctv', 'power', 'cleaning', 'water'],
    roomOptions: [
      { type: 'AC', sharing: 1, price: 10000 },
      { type: 'AC', sharing: 2, price: 8500 },
      { type: 'Non-AC', sharing: 2, price: 7500 },
      { type: 'Non-AC', sharing: 3, price: 7000 },
    ],
    rateCard: {
        ac: { day: 450, twoDays: 850, weekly: 2800, monthly: 8500, yearly: 90000 },
        nonAc: { day: 350, twoDays: 650, weekly: 2200, monthly: 7000, yearly: 75000 },
    },
    inclusions: [ '3-Time Meals', 'Wi-Fi', 'Laundry Service', 'Daily Cleaning', 'Security' ],
    paymentOptions: [ 'UPI', 'Credit/Debit Card', 'Cash' ],
    foodMenu: [
       { day: 'Monday', breakfast: 'Pesarattu', lunch: 'Veg Thali', dinner: 'Roti, Aloo Gobi' },
       { day: 'Tuesday', breakfast: 'Idli', lunch: 'Tomato Rice', dinner: 'Rice, Egg Curry' },
       { day: 'Wednesday', breakfast: 'Upma', lunch: 'Veg Biryani', dinner: 'Chapati, Dal Tadka' },
       { day: 'Thursday', breakfast: 'Dosa', lunch: 'Sambar Rice', dinner: 'Roti, Paneer Masala' },
       { day: 'Friday', breakfast: 'Poori', lunch: 'Veg Fried Rice', dinner: 'Rice, Fish Curry' },
       { day: 'Saturday', breakfast: 'Vada', lunch: 'Special Thali', dinner: 'Chapati, Mixed Veg' },
       { day: 'Sunday', breakfast: 'Masala Dosa', lunch: 'Chicken Biryani', dinner: 'Rice, Dal Fry' },
    ],
    securityDeposit: 2500,
    securityInfo: ['24/7 Security Guard', 'CCTV Surveillance', 'Biometric Entry', 'No Smoking Zone'],
  },
  {
    id: 3,
    name: 'Veerabhadra Hostel',
    location: 'Vijayawada',
    fullAddress: 'Vaddeswaram, Vijayawada, Andhra Pradesh',
    description: 'A modern, clean, and minimalist hostel located in the bustling student district, offering a peaceful environment for studying and relaxation.',
    price: 6000,
    rating: 4.7,
    reviews: 2100,
    images: [
      'https://easy-peasy.ai/cdn-cgi/image/quality=80,format=auto,width=700/https://media.easy-peasy.ai/e4140f38-3ec3-484c-988b-f867f3aebffa/75dea8e9-7b18-4924-b9c8-c3e1c9c2fcd6.png',
      'https://easy-peasy.ai/cdn-cgi/image/quality=80,format=auto,width=700/https://media.easy-peasy.ai/e4140f38-3ec3-484c-988b-f867f3aebffa/75dea8e9-7b18-4924-b9c8-c3e1c9c2fcd6.png',
      'https://easy-peasy.ai/cdn-cgi/image/quality=80,format=auto,width=700/https://media.easy-peasy.ai/e4140f38-3ec3-484c-988b-f867f3aebffa/75dea8e9-7b18-4924-b9c8-c3e1c9c2fcd6.png',
    ],
    facilities: ['wifi', 'ac', 'cleaning', 'study', 'cctv', 'water', 'power'],
     roomOptions: [
      { type: 'AC', sharing: 2, price: 7500 },
      { type: 'AC', sharing: 4, price: 6500 },
      { type: 'Non-AC', sharing: 4, price: 6000 },
    ],
    rateCard: {
        ac: { day: 380, twoDays: 700, weekly: 2300, monthly: 7500, yearly: 80000 },
        nonAc: { day: 280, twoDays: 550, weekly: 1800, monthly: 6000, yearly: 65000 },
    },
    inclusions: [ '2-Time Meals', 'Wi-Fi', 'Daily Cleaning', 'Study Room Access' ],
    paymentOptions: [ 'UPI', 'Cash' ],
    foodMenu: [
       { day: 'Monday', breakfast: 'Idli', lunch: 'Veg Thali', dinner: 'Roti, Dal' },
       { day: 'Tuesday', breakfast: 'Dosa', lunch: 'Curd Rice', dinner: 'Rice, Veg Curry' },
       { day: 'Wednesday', breakfast: 'Poori', lunch: 'Veg Pulao', dinner: 'Chapati, Chana Masala' },
       { day: 'Thursday', breakfast: 'Upma', lunch: 'Sambar Rice', dinner: 'Roti, Aloo Matar' },
       { day: 'Friday', breakfast: 'Paratha', lunch: 'Lemon Rice', dinner: 'Rice, Egg Bhurji' },
       { day: 'Saturday', breakfast: 'Vada', lunch: 'Fried Rice', dinner: 'Chapati, Mix Veg' },
       { day: 'Sunday', breakfast: 'Special Dosa', lunch: 'Veg Biryani', dinner: 'Rice, Paneer Curry' },
    ],
    securityDeposit: 1500,
    securityInfo: ['CCTV in Common Areas', 'Warden on Floor', 'Strict Visitor Policy'],
  },
  {
    id: 4,
    name: 'Meenakshi Boys Hostel',
    location: 'Vijayawada',
    fullAddress: 'Vaddeswaram, Vijayawada, Andhra Pradesh',
    description: 'A comfortable and affordable hostel, perfect for students on a budget. Offers all essential services for a pleasant stay.',
    price: 5500,
    rating: 4.6,
    reviews: 1543,
    images: [
      'https://rerender.s3.amazonaws.com/render/66a7398f8adbedd5ffa259b6/ba312805-1b95-42bc-b245-8ed6fbb3f96c-1707668438-0-fix.jpg?nonce=1722235380324',
      'https://rerender.s3.amazonaws.com/render/66a7398f8adbedd5ffa259b6/ba312805-1b95-42bc-b245-8ed6fbb3f96c-1707668438-0-fix.jpg?nonce=1722235380324',
      'https://rerender.s3.amazonaws.com/render/66a7398f8adbedd5ffa259b6/ba312805-1b95-42bc-b245-8ed6fbb3f96c-1707668438-0-fix.jpg?nonce=1722235380324',
    ],
    facilities: ['wifi', 'pool', 'kitchen', 'food', 'cctv', 'water'],
    roomOptions: [
      { type: 'AC', sharing: 3, price: 6500 },
      { type: 'Non-AC', sharing: 3, price: 5800 },
      { type: 'Non-AC', sharing: 4, price: 5500 },
    ],
    rateCard: {
        ac: { day: 350, twoDays: 650, weekly: 2100, monthly: 6500, yearly: 70000 },
        nonAc: { day: 250, twoDays: 450, weekly: 1600, monthly: 5500, yearly: 60000 },
    },
    inclusions: [ '3-Time Meals', 'Wi-Fi', 'Filtered Water' ],
    paymentOptions: [ 'Cash Only' ],
    foodMenu: [
       { day: 'Monday', breakfast: 'Bread & Omelette', lunch: 'Rice, Dal, Veg Fry', dinner: 'Chapati, Aloo Curry' },
       { day: 'Tuesday', breakfast: 'Dosa', lunch: 'Veg Pulao', dinner: 'Rice, Sambar' },
       { day: 'Wednesday', breakfast: 'Idli', lunch: 'Lemon Rice', dinner: 'Roti, Paneer' },
       { day: 'Thursday', breakfast: 'Upma', lunch: 'Veg Thali', dinner: 'Rice, Egg Curry' },
       { day: 'Friday', breakfast: 'Poori', lunch: 'Fried Rice', dinner: 'Chapati, Dal' },
       { day: 'Saturday', breakfast: 'Paratha', lunch: 'Curd Rice', dinner: 'Rice, Veg Curry' },
       { day: 'Sunday', breakfast: 'Masala Dosa', lunch: 'Special Lunch', dinner: 'Roti, Chana Masala' },
    ],
    securityDeposit: 1000,
    securityInfo: ['24/7 Security', 'Entry Register', 'Night Warden'],
  },
  {
    id: 5,
    name: 'Bhargava Boys Hostel',
    location: 'Guntur',
    fullAddress: 'Brodipet, Guntur, Andhra Pradesh',
    description: 'A well-maintained and disciplined hostel, preferred by students looking for a quiet and studious atmosphere. Close to major coaching centers.',
    price: 6800,
    rating: 4.8,
    reviews: 987,
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    facilities: ['wifi', 'kitchen', 'study', 'cleaning', 'power', 'purifier', 'laundry'],
    roomOptions: [
      { type: 'AC', sharing: 2, price: 8200 },
      { type: 'Non-AC', sharing: 2, price: 7200 },
      { type: 'Non-AC', sharing: 3, price: 6800 },
    ],
    rateCard: {
        ac: { day: 420, twoDays: 800, weekly: 2600, monthly: 8200, yearly: 88000 },
        nonAc: { day: 320, twoDays: 620, weekly: 2100, monthly: 6800, yearly: 72000 },
    },
    inclusions: [ '3-Time Meals', 'Wi-Fi', 'Power Backup', 'Laundry', 'Study Hall' ],
    paymentOptions: [ 'UPI', 'Net Banking' ],
    foodMenu: [
       { day: 'Monday', breakfast: 'Idli', lunch: 'Full Meals', dinner: 'Roti, Veg Curry' },
       { day: 'Tuesday', breakfast: 'Dosa', lunch: 'Pulihora', dinner: 'Rice, Dal' },
       { day: 'Wednesday', breakfast: 'Upma', lunch: 'Veg Biryani', dinner: 'Chapati, Paneer' },
       { day: 'Thursday', breakfast: 'Poori', lunch: 'Sambar Rice', dinner: 'Roti, Aloo' },
       { day: 'Friday', breakfast: 'Paratha', lunch: 'Fried Rice', dinner: 'Rice, Egg Curry' },
       { day: 'Saturday', breakfast: 'Vada', lunch: 'Special Meals', dinner: 'Chapati, Gobi Curry' },
       { day: 'Sunday', breakfast: 'Masala Dosa', lunch: 'Non-veg Biryani', dinner: 'Rice, Dal' },
    ],
    securityDeposit: 2000,
    securityInfo: ['Biometric System', 'CCTV Cameras', 'On-site Warden', 'Visitor Time Limits'],
  },
  {
    id: 6,
    name: 'City Center Pods',
    location: 'Bengaluru',
    fullAddress: 'Koramangala, Bengaluru, Karnataka',
    description: 'Affordable and futuristic pod-style accommodation in the heart of the city. Perfect for tech professionals and students.',
    price: 9000,
    rating: 4.5,
    reviews: 3200,
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    facilities: ['wifi', 'ac', 'gym', 'kitchen', 'laundry', 'cctv'],
    roomOptions: [
      { type: 'AC', sharing: 1, price: 12000 },
      { type: 'AC', sharing: 2, price: 9000 },
    ],
    rateCard: {
        ac: { day: 500, twoDays: 950, weekly: 3000, monthly: 9000, yearly: 95000 },
        nonAc: { day: 400, twoDays: 750, weekly: 2500, monthly: 7500, yearly: 80000 },
    },
    inclusions: [ 'Breakfast', 'High-Speed Wi-Fi', 'Gym Access', 'Co-working Space' ],
    paymentOptions: [ 'All Digital Payments', 'Credit Card EMI' ],
    foodMenu: [
      { day: 'Monday', breakfast: 'Oats', lunch: 'Salad Bar', dinner: 'Quinoa Bowl' },
      { day: 'Tuesday', breakfast: 'Smoothie', lunch: 'Sandwich', dinner: 'Pasta' },
      { day: 'Wednesday', breakfast: 'Avocado Toast', lunch: 'Wrap', dinner: 'Stir Fry' },
      { day: 'Thursday', breakfast: 'Yogurt Bowl', lunch: 'Soup', dinner: 'Tacos' },
      { day: 'Friday', breakfast: 'Pancakes', lunch: 'Pizza Slice', dinner: 'Burger' },
      { day: 'Saturday', breakfast: 'Muffins', lunch: 'Brunch Buffet', dinner: 'Community BBQ' },
      { day: 'Sunday', breakfast: 'Waffles', lunch: 'Roast Dinner', dinner: 'Leftovers Night' },
    ],
    securityDeposit: 3000,
    securityInfo: ['Key Card Access', '24/7 Reception', 'Secure Lockers'],
  },
  {
    id: 7,
    name: 'Green Leaf Hostel',
    location: 'Pune',
    fullAddress: 'Viman Nagar, Pune, Maharashtra',
    description: 'Immerse yourself in a calm, green environment. Our eco-friendly hostel is perfect for those who love peace and quiet.',
    price: 6000,
    rating: 4.9,
    reviews: 750,
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    facilities: ['wifi', 'pool', 'gym', 'purifier', 'cleaning', 'parking'],
    roomOptions: [
        { type: 'AC', sharing: 2, price: 7500 },
        { type: 'Non-AC', sharing: 2, price: 6500 },
        { type: 'Non-AC', sharing: 4, price: 6000 },
    ],
    rateCard: {
        ac: { day: 380, twoDays: 720, weekly: 2400, monthly: 7500, yearly: 80000 },
        nonAc: { day: 300, twoDays: 580, weekly: 1900, monthly: 6000, yearly: 65000 },
    },
    inclusions: [ 'Breakfast', 'Yoga Classes', 'Filtered Water', 'Garden Access' ],
    paymentOptions: [ 'UPI', 'Cash' ],
    foodMenu: [
       { day: 'Monday', breakfast: 'Poha', lunch: 'Maharashtrian Thali', dinner: 'Roti, Baingan Bharta' },
       { day: 'Tuesday', breakfast: 'Upma', lunch: 'Dal Khichdi', dinner: 'Rice, Usal' },
       { day: 'Wednesday', breakfast: 'Misal Pav', lunch: 'Pithla Bhakri', dinner: 'Chapati, Matki Sabzi' },
       { day: 'Thursday', breakfast: 'Sabudana Khichdi', lunch: 'Veg Kolhapuri', dinner: 'Roti, Dal' },
       { day: 'Friday', breakfast: 'Thalipeeth', lunch: 'Bharli Vangi', dinner: 'Rice, Curry' },
       { day: 'Saturday', breakfast: 'Kande Pohe', lunch: 'Special Veg Thali', dinner: 'Chapati, Shev Bhaji' },
       { day: 'Sunday', breakfast: 'Puri Bhaji', lunch: 'Masale Bhat', dinner: 'Rice, Dal Tadka' },
    ],
    securityDeposit: 1500,
    securityInfo: ['Gated Community', 'Security Guard', 'CCTV'],
  },
  {
    id: 8,
    name: 'The Scholar\'s Den',
    location: 'Chennai',
    fullAddress: 'T. Nagar, Chennai, Tamil Nadu',
    description: 'A quiet and comfortable hostel designed for students. Features a library, study areas, and high-speed internet for all your academic needs.',
    price: 7200,
    rating: 4.7,
    reviews: 1100,
    images: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
    ],
    facilities: ['wifi', 'kitchen', 'parking', 'study', 'power', 'cctv', 'ac'],
     roomOptions: [
        { type: 'AC', sharing: 1, price: 10000 },
        { type: 'AC', sharing: 2, price: 8500 },
        { type: 'Non-AC', sharing: 2, price: 7200 },
    ],
    rateCard: {
        ac: { day: 480, twoDays: 900, weekly: 2900, monthly: 8500, yearly: 92000 },
        nonAc: { day: 360, twoDays: 700, weekly: 2300, monthly: 7200, yearly: 78000 },
    },
    inclusions: [ 'South Indian Breakfast', 'High-Speed Wi-Fi', 'Library Access', '24/7 Power' ],
    paymentOptions: [ 'UPI', 'Card', 'Cash' ],
    foodMenu: [
       { day: 'Monday', breakfast: 'Pongal, Vada', lunch: 'Sambar, Rice, Poriyal', dinner: 'Chapati, Kurma' },
       { day: 'Tuesday', breakfast: 'Idiyappam', lunch: 'Lemon Rice, Aviyal', dinner: 'Dosa, Chutney' },
       { day: 'Wednesday', breakfast: 'Kichadi', lunch: 'Kara Kuzhambu, Rice', dinner: 'Roti, Dal' },
       { day: 'Thursday', breakfast: 'Rava Dosa', lunch: 'Veg Biryani, Raita', dinner: 'Idli, Sambar' },
       { day: 'Friday', breakfast: 'Ven Pongal', lunch: 'Vatha Kuzhambu, Rice', dinner: 'Chapati, Egg Curry' },
       { day: 'Saturday', breakfast: 'Poori Masala', lunch: 'Full Meals', dinner: 'Kothu Parotta' },
       { day: 'Sunday', breakfast: 'Aappam', lunch: 'Chicken Curry, Rice', dinner: 'Dosa, Sambar' },
    ],
    securityDeposit: 2000,
    securityInfo: ['24/7 Security', 'Biometric Entry', 'Floor Warden'],
  },
];

export const featuredHostels = allHostels.slice(0, 4);

export const getHostelById = (id: number) => allHostels.find((h) => h.id === id);
